server {
    # -----------------------------------------------------
    # Server Configuration
    # -----------------------------------------------------
    listen 80;
    server_name localhost;
    # charset utf-8;

    # -----------------------------------------------------
    # Document Root
    # -----------------------------------------------------
    root /var/www/html/public;
    index index.php index.html;

    # -----------------------------------------------------
    # Route Requests to CodeIgniter
    # -----------------------------------------------------
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # -----------------------------------------------------
    # Forward PHP Requests to PHP-FPM
    # -----------------------------------------------------
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors on;
    }

    # -----------------------------------------------------
    # Deny Access to Hidden Files
    # -----------------------------------------------------
    location ~ /\. {
        deny all;
    }
}